baseURL = 'https://www.aswarbs.github.io/'
languageCode = 'en-us'
title = 'Amber Swarbrick'
disableKinds = ['taxonomy', 'term']
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2


  [[menu.main]]
    identifier = "hackathons"
    name = "Hackathons"
    url = "/hackathons/"
    weight = 3


[caches]
  [caches.images]
    dir = ':cacheDir/images'