baseURL = 'https://www.amber.wiki/'
languageCode = 'en-us'
title = 'Amber Swarbrick'
disableKinds = ['taxonomy', 'term']
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "hackathons"
    name = "Hackathons"
    url = "/hackathons/"
    weight = 2

  [[menu.main]]
    identifier = "Projects"
    name = "Projects"
    url = "/projects/"
    weight = 3
